### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke interface method 'retrofit.Call api.PGAPI.makeMOTOPayment(com.squareup.okhttp.RequestBody)' on a null object reference at client.PGClient.makeMOTOPayment(PGClient.java:102)

### ISSUE THREAD

**Issue by dharmendrajadon** [citruspay/citrus-android-sdk#16]
java.lang.NullPointerException: Attempt to invoke interface method 'retrofit.Call api.PGAPI.makeMOTOPayment(com.squareup.okhttp.RequestBody)' on a null object reference
at client.PGClient.makeMOTOPayment(PGClient.java:102)
at com.citrus.sdk.RetrofitAPIWrapper.makeMOTOPayment(RetrofitAPIWrapper.java:856)
at com.citrus.sdk.CitrusClient.makeMOTOPayment(CitrusClient.java:1257)
at com.citrus.payment.PG.retrofitCharge(PG.java:416)
at com.citrus.payment.PG.formjson(PG.java:396)
at com.citrus.payment.PG.validate(PG.java:218)
at com.citrus.payment.PG.charge(PG.java:145)
at com.citrus.sdk.CitrusActivity.proceedToPayment(CitrusActivity.java:478)
at com.citrus.sdk.CitrusActivity.access$1900(CitrusActivity.java:89)
at com.citrus.sdk.CitrusActivity$5.success(CitrusActivity.java:438)
at com.citrus.sdk.CitrusActivity$5.success(CitrusActivity.java:429)
at client.BaseClient.sendResponse(BaseClient.java:113)
at client.PGClient$15.success(PGClient.java:743)
at client.PGClient$15.success(PGClient.java:740)
at com.citrus.sdk.GetJSONBill.onPostExecute(GetJSONBill.java:76)
at com.citrus.sdk.GetJSONBill.onPostExecute(GetJSONBill.java:22)
at android.os.AsyncTask.finish(AsyncTask.java:632)
at android.os.AsyncTask.access$600(AsyncTask.java:177)
at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:645)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:135)
at android.app.ActivityThread.main(ActivityThread.java:5312)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:901)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:696)

**Comment by MangeshKadam** [comment]
@dharmendrajadon  - are you trying saved card/bank payment or its new bank/card transaction?
