### ISSUE TITLE
NPE in CitrusActivity.java

### ISSUE THREAD

**Issue by milindbableshwar** [citruspay/citrus-android-sdk#17]
`Fatal Exception: java.lang.NullPointerException
       at com.citrus.sdk.CitrusActivity$4.onFinish(CitrusActivity.java:400)
       at android.os.CountDownTimer$1.handleMessage(CountDownTimer.java:118)
       at android.os.Handler.dispatchMessage(Handler.java:110)
       at android.os.Looper.loop(Looper.java:193)
       at android.app.ActivityThread.main(ActivityThread.java:5349)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:835)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:651)
       at dalvik.system.NativeStart.main(NativeStart.java)`

**Comment by milindbableshwar** [comment]
Version: com.citrus.sdk:payment-sdk:3.4.3:retrofitoldRelease@aar
