### ISSUE TITLE
NPE during PaymentType.getIntentAction()

### ISSUE THREAD

**Issue by milindbableshwar** [citruspay/citrus-android-sdk#18]
`Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.citrus.sdk.payment.PaymentType.getIntentAction()' on a null object reference
       at com.citrus.sdk.CitrusActivity.sendResult(CitrusActivity.java:759)
       at com.citrus.sdk.CitrusActivity.access$2100(CitrusActivity.java:89)
       at com.citrus.sdk.CitrusActivity$5.error(CitrusActivity.java:448)
       at client.BaseClient.sendError(BaseClient.java:124)
       at client.PGClient$15.error(PGClient.java:667)
       at com.citrus.sdk.GetJSONBill.onPostExecute(GetJSONBill.java:78)
       at com.citrus.sdk.GetJSONBill.onPostExecute(GetJSONBill.java:22)
       at android.os.AsyncTask.finish(AsyncTask.java:636)
       at android.os.AsyncTask.access$500(AsyncTask.java:177)
       at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:653)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:145)
       at android.app.ActivityThread.main(ActivityThread.java:6912)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)`

**Comment by Pratima-Gadekar** [comment]
@milindbableshwar could you explain your error?

**Comment by milindbableshwar** [comment]
@Pratima-Gadekar : I do not know the context in which this exception is being thrown. Isn't the stack trace sufficient ?
