### ISSUE TITLE
SDK crashes after payment(seen mainly for HDFC cards)

### ISSUE THREAD

**Issue by shijo01** [citruspay/citrus-android-sdk#32]
com.citrus.sdk.CitrusActivity$4.onFinish

java.lang.NullPointerException: Attempt to invoke virtual method 'void android.webkit.WebView.loadUrl(java.lang.String)' on a null object reference

**Comment by shijo01** [comment]
here is the full crash log

java.lang.NullPointerException: Attempt to invoke virtual method 'void android.webkit.WebView.loadUrl(java.lang.String)' on a null object reference
	at com.citrus.sdk.CitrusActivity$4.onFinish(Unknown Source)
	at android.os.CountDownTimer$1.handleMessage(CountDownTimer.java:127)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5343)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)
