### ISSUE TITLE
App Crashing

### ISSUE THREAD

**Issue by rameshkec85** [citruspay/citrus-android-sdk#38]
java.lang.RuntimeException: Error receiving broadcast Intent { act=android.provider.Telephony.SMS_RECEIVED flg=0x8000010 (has extras) } in com.citruspay.citrusbrowser.listener.e@fd43268
	at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:893)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5441)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:738)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:628)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'org.json.JSONArray com.citruspay.citrusbrowser.core.f$a.c()' on a null object reference
	at com.citruspay.citrusbrowser.listener.e.onReceive(Unknown Source)
	at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:883)
	... 7 more

**Comment by rameshkec85** [comment]
This is too bad. Citrus team is not looking into issues!!!  These are basic issues which are facing from customers. 👎

**Comment by sankar-novel** [comment]
Did you get any solution for the above issue?

**Comment by rameshkec85** [comment]
@sankar-novel  No
