### ISSUE TITLE
App Crashing on deleting card 

### ISSUE THREAD

**Issue by alkesh26** [citruspay/citrus-android-sdk#5]
please update the sdk 
on line  3013 of the latest citrus sdk version (3.1.7)  (error.getResponse().getStatus() == HttpURLConnection.HTTP_INTERNAL_ERROR)  here 
erroe.getResponse is NULL

```javascript

        Process: com.flutterbee.tinyowl.staging, PID: 19952
        java.lang.NullPointerException: Attempt to invoke virtual method 'int retrofit.client.Response.getStatus()' on a null object reference
        at com.citrus.sdk.CitrusClient.sendError(CitrusClient.java:3013)
        at com.citrus.sdk.CitrusClient.access$1100(CitrusClient.java:117)
        at com.citrus.sdk.CitrusClient$26$1.failure(CitrusClient.java:1981)
        at retrofit.CallbackRunnable$2.run(CallbackRunnable.java:53)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5343)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)
```

**Comment by neeraj-citrus** [comment]
Anyone looked at this?

**Comment by MangeshKadam** [comment]
Hi Alkesh,
we will fix this asap and will update the SDK.

**Comment by MangeshKadam** [comment]
@alkesh26 - do let me know if this is fixed so that I can close this issue.
