### ISSUE TITLE
Latest citrus sdk support the earlier version of android 5.0

### ISSUE THREAD

**Issue by Bhavdip** [citruspay/citrus-android-sdk#9]
Hello, 

I downloaded the latest version of citrus sdk version. Try to run the sample application into the android version 4.0 but application could not able to run. Let me know Citrus SDK can provide the support of earlier version of 5.0? 

I got the chance to look into the code this [link ](https://github.com/citruspay/citrus-android-sdk/blob/master/citrus-library/AndroidManifest.xml). I see that the min api version is 9. 

Kindly please help me to understand the min support of citrus of android SDK.

Thank you.

**Comment by sourabh-verma-citruspay** [comment]
We do support earlier version of Android SDK all the way till API level 9 (Android 2.3). Can you provide the error log and answer these questions.
1) Is gradle build happening for you
2) Are all dependencies being built.
3) Which Retrofit version, you are using
4) logs from logcat.

**Comment by Bhavdip** [comment]
1. Actually I downloaded the latest SDK but could not able to open into the android studio. Then i try to look into the structure of the code see that project could not able to import into the android studio. Create the new android studios project put all dependencies and all sample code classes into my sample project including the package name. It is working fine. but when I try to run into the android version 4.1 it's not working. 

2. I could not able to run the sample sdk code into my android studio 1.0

3. I am using Retrofit 2.0

4. I will edit later on 

Thank you.

**Comment by Bhavdip** [comment]
Below you can find the build.gradle of my sample citrus project
[citrus-sample](https://github.com/Bhavdip/citrus-sample/blob/master/app/build.gradle)

**Comment by Bhavdip** [comment]
02-18 10:48:13.190 18884-18884/com.citrus.sample E/Trace: error opening trace file: No such file or directory (2)
02-18 10:48:13.190 18884-18884/com.citrus.sample D/ActivityThread: setTargetHeapUtilization:0.25
02-18 10:48:13.190 18884-18884/com.citrus.sample D/ActivityThread: setTargetHeapIdealFree:8388608
02-18 10:48:13.190 18884-18884/com.citrus.sample D/ActivityThread: setTargetHeapConcurrentStart:2097152
02-18 10:48:13.300 18884-18884/com.citrus.sample W/dalvikvm: VFY: unable to find class referenced in signature (Landroid/view/SearchEvent;)
02-18 10:48:13.300 18884-18884/com.citrus.sample W/dalvikvm: VFY: unable to resolve interface method 18202: Landroid/view/Window$Callback;.onSearchRequested (Landroid/view/SearchEvent;)Z
02-18 10:48:13.300 18884-18884/com.citrus.sample W/dalvikvm: VFY: unable to resolve interface method 18206: Landroid/view/Window$Callback;.onWindowStartingActionMode (Landroid/view/ActionMode$Callback;I)Landroid/view/ActionMode;
02-18 10:48:13.390 18884-18884/com.citrus.sample W/dalvikvm: VFY: unable to resolve virtual method 18098: Landroid/view/ViewGroup;.onRtlPropertiesChanged (I)V
02-18 10:48:13.410 18884-18884/com.citrus.sample W/dalvikvm: VFY: unable to resolve virtual method 545: Landroid/content/res/TypedArray;.getChangingConfigurations ()I
02-18 10:48:13.410 18884-18884/com.citrus.sample W/dalvikvm: VFY: unable to resolve virtual method 567: Landroid/content/res/TypedArray;.getType (I)I
02-18 10:48:13.510 18884-18884/com.citrus.sample E/dalvikvm: Could not find class 'com.facebook.crypto.Entity', referenced from method com.citrus.sdk.CitrusClient.getCVVOfFingerPrint
02-18 10:48:13.510 18884-18884/com.citrus.sample W/dalvikvm: VFY: unable to resolve new-instance 2717 (Lcom/facebook/crypto/Entity;) in Lcom/citrus/sdk/CitrusClient;
02-18 10:48:13.510 18884-18884/com.citrus.sample W/dalvikvm: VFY: unable to resolve exception class 2719 (Lcom/facebook/crypto/exception/KeyChainException;)
02-18 10:48:13.510 18884-18884/com.citrus.sample W/dalvikvm: VFY: unable to find exception handler at addr 0x58
02-18 10:48:13.510 18884-18884/com.citrus.sample W/dalvikvm: VFY:  rejected Lcom/citrus/sdk/CitrusClient;.getCVVOfFingerPrint (Lcom/citrus/sdk/payment/CardOption;)Ljava/lang/String;
02-18 10:48:13.510 18884-18884/com.citrus.sample W/dalvikvm: VFY:  rejecting opcode 0x0d at 0x0058
02-18 10:48:13.510 18884-18884/com.citrus.sample W/dalvikvm: VFY:  rejected Lcom/citrus/sdk/CitrusClient;.getCVVOfFingerPrint (Lcom/citrus/sdk/payment/CardOption;)Ljava/lang/String;
02-18 10:48:13.510 18884-18884/com.citrus.sample W/dalvikvm: Verifier rejected class Lcom/citrus/sdk/CitrusClient;
02-18 10:48:13.510 18884-18884/com.citrus.sample W/dalvikvm: threadid=1: thread exiting with uncaught exception (group=0x40c51438)
02-18 10:48:13.520 18884-18884/com.citrus.sample E/AndroidRuntime: FATAL EXCEPTION: main
java.lang.VerifyError: com/citrus/sdk/CitrusClient
    at com.citrus.sample.UIActivity.onCreate(UIActivity.java:59)
    at android.app.Activity.performCreate(Activity.java:5008)
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1079)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2031)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2092)
    at android.app.ActivityThread.access$600(ActivityThread.java:133)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1203)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:137)
    at android.app.ActivityThread.main(ActivityThread.java:4794)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:511)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:556)
    at dalvik.system.NativeStart.main(Native Method)

**Comment by Bhavdip** [comment]
Finally I could able to build and run the application in android 4.0 but I found the exception. 

`02-18 11:03:38.320 23925-23925/com.citrus.sample E/AndroidRuntime: FATAL EXCEPTION: main
                                                                   java.lang.VerifyError: com/citrus/sdk/CitrusClient
                                                                       at com.citrus.sample.UIActivity.onCreate(UIActivity.java:59)
                                                                       at android.app.Activity.performCreate(Activity.java:5008)
                                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1079)
                                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2031)
                                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2092)
                                                                       at android.app.ActivityThread.access$600(ActivityThread.java:133)
                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1203)
                                                                       at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                       at android.os.Looper.loop(Looper.java:137)
                                                                       at android.app.ActivityThread.main(ActivityThread.java:4794)
                                                                       at java.lang.reflect.Method.invokeNative(Native Method)
                                                                       at java.lang.reflect.Method.invoke(Method.java:511)
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:556)
                                                                       at dalvik.system.NativeStart.main(Native Method)`

**Comment by salilgodbole** [comment]
Hi,

I went through the build.gradle you have provided.
The error occurs since there are multiple versions of Citrus SDK and other dependencies.
Remove following line from your build.gradle (line no.33)
 compile fileTree(include: ['*.jar'], dir: 'libs')

Adding this line makes the Citrus SDK and other dependencies being added twice which is resulting in the error.

**Comment by Bhavdip** [comment]
Hi salilgodbole,

Remove the line from build.gradle same exception while run the application. But one thing found that exception occur in com.facebook.conceal:conceal "Could not find class 'com.facebook.crypto.Entity',".

See that if i add "com.facebook.conceal:conceal:1.0.1@aar" application can run successfully in both android 40 and android 5.0 but again if I add latest version "com.facebook.conceal:conceal:1.0.3" the same exception occurred.

Any idea the correct version should I have to add into the project?

Thanks for the help.

**Comment by salilgodbole** [comment]
You should use 1.0.1 version for conceal library.

Thanks,
*Salil Godbole*
Skype id: salilgodbole

**Comment by Bhavdip** [comment]
> You should use 1.0.1 version for conceal library.

Thank you for the help. Now can able to run in all devices android 6.0.1 android 5.0, android 4.4.2. 

You can close this issue.

**Comment by salilgodbole** [comment]
Welcome :)


Thanks,
*Salil Godbole*
Skype id: salilgodbole
